version: 2
jobs:
  build:
    working_directory: ~/todo-hooks
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn ci
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.yarn
      - run:
          name: Run Tests
          command: yarn test
